/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    files: File;
    datasets: Dataset;
    configs: Config1;
    jobs: Job;
    documents: Document;
    summaries: Summary;
    sessions: Session;
    'conversation-turns': ConversationTurn;
    geminiMetadataCache: GeminiMetadataCache;
    claudeConfigCache: ClaudeConfigCache;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    configs: ConfigsSelect<false> | ConfigsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    summaries: SummariesSelect<false> | SummariesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'conversation-turns': ConversationTurnsSelect<false> | ConversationTurnsSelect<true>;
    geminiMetadataCache: GeminiMetadataCacheSelect<false> | GeminiMetadataCacheSelect<true>;
    claudeConfigCache: ClaudeConfigCacheSelect<false> | ClaudeConfigCacheSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'admin' | 'analyst' | 'viewer';
  /**
   * Deactivated users are barred from authenticating across all routes.
   */
  isActive: boolean;
  /**
   * Timestamp of last successful authentication.
   */
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  /**
   * SHA-256 of the raw file bytes. File identity, not the filename.
   */
  sha256?: string | null;
  storagePath?: string | null;
  uploadedBy?: (number | null) | User;
  dataBase64?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  name: string;
  currentFile?: (number | null) | File;
  currentFileHash?: string | null;
  status: 'processing' | 'ready' | 'failed' | 'updating';
  tableNames?:
    | {
        tableName: string;
        id?: string | null;
      }[]
    | null;
  totalRows?: number | null;
  /**
   * The normalized dataset: exactly the tables[] and relationships[] arrays from the Section 14 contract. Written only after full validation succeeds.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The technical error from the most recent failed Job against this dataset, denormalized here so the dashboard route can show why an upload failed without a second query. Cleared whenever a job against this dataset next reaches ready/completed.
   */
  lastError?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configs".
 */
export interface Config1 {
  id: number;
  dataset: number | Dataset;
  version: number;
  /**
   * Dashboard config. Never contains dataset rows.
   */
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  insights?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generatedBy: 'initial_auto_generation' | 'prompt_edit' | 'direct_edit' | 'initial_fallback';
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  file: number | File;
  dataset?: (number | null) | Dataset;
  document?: (number | null) | Document;
  fileHash?: string | null;
  intentPrompt?: string | null;
  status: 'queued' | 'processing' | 'validating' | 'generating_config' | 'completed' | 'failed' | 'duplicate_noop';
  retryCount: number;
  error?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  name: string;
  currentFile?: (number | null) | File;
  currentFileHash?: string | null;
  status: 'processing' | 'ready' | 'failed' | 'updating';
  /**
   * The normalized narrative document: documentId, sourceFile, fullText, and sections[] from the Section 10.0 Step 2 contract. Written only after full validation succeeds.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The technical error from the most recent failed job against this document, including the explicit 'this file appears tabular' verdict when Gemini classifies it that way.
   */
  lastError?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "summaries".
 */
export interface Summary {
  id: number;
  document: number | Document;
  version: number;
  /**
   * The full keyPoints[] list as of this version (Section 10.0 Step 3 contract).
   */
  keyPoints?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generatedBy: 'initial_summary' | 'expand' | 'prompt_edit';
  expandedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  name: string;
  datasets?: (number | Dataset)[] | null;
  documents?: (number | Document)[] | null;
  status: 'synthesizing' | 'ready' | 'failed';
  /**
   * { findings: ResolvedSessionFindingShape[] }. Written only after every finding resolves and verifies; an empty findings array is a valid, common result.
   */
  overview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The technical error from the most recent failed synthesis attempt.
   */
  lastError?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-turns".
 */
export interface ConversationTurn {
  id: number;
  session: number | Session;
  kind: 'chat' | 'edit';
  message: string;
  targetSourceKind?: ('dataset' | 'document') | null;
  targetSourceId?: string | null;
  status: 'answered' | 'edit_applied' | 'needs_clarification' | 'error';
  /**
   * The full result shown to the user: directAnswer+metrics+citations for chat, configVersion/summaryVersion for an applied edit, the clarifying question for needs_clarification, or the error message.
   */
  response?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geminiMetadataCache".
 */
export interface GeminiMetadataCache {
  id: number;
  hash: string;
  metadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claudeConfigCache".
 */
export interface ClaudeConfigCache {
  id: number;
  hash: string;
  config:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'configs';
        value: number | Config1;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'summaries';
        value: number | Summary;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'conversation-turns';
        value: number | ConversationTurn;
      } | null)
    | ({
        relationTo: 'geminiMetadataCache';
        value: number | GeminiMetadataCache;
      } | null)
    | ({
        relationTo: 'claudeConfigCache';
        value: number | ClaudeConfigCache;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  isActive?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  sha256?: T;
  storagePath?: T;
  uploadedBy?: T;
  dataBase64?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  name?: T;
  currentFile?: T;
  currentFileHash?: T;
  status?: T;
  tableNames?:
    | T
    | {
        tableName?: T;
        id?: T;
      };
  totalRows?: T;
  data?: T;
  lastError?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configs_select".
 */
export interface ConfigsSelect<T extends boolean = true> {
  dataset?: T;
  version?: T;
  config?: T;
  insights?: T;
  generatedBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  file?: T;
  dataset?: T;
  document?: T;
  fileHash?: T;
  intentPrompt?: T;
  status?: T;
  retryCount?: T;
  error?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  name?: T;
  currentFile?: T;
  currentFileHash?: T;
  status?: T;
  data?: T;
  lastError?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "summaries_select".
 */
export interface SummariesSelect<T extends boolean = true> {
  document?: T;
  version?: T;
  keyPoints?: T;
  generatedBy?: T;
  expandedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  name?: T;
  datasets?: T;
  documents?: T;
  status?: T;
  overview?: T;
  lastError?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-turns_select".
 */
export interface ConversationTurnsSelect<T extends boolean = true> {
  session?: T;
  kind?: T;
  message?: T;
  targetSourceKind?: T;
  targetSourceId?: T;
  status?: T;
  response?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geminiMetadataCache_select".
 */
export interface GeminiMetadataCacheSelect<T extends boolean = true> {
  hash?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claudeConfigCache_select".
 */
export interface ClaudeConfigCacheSelect<T extends boolean = true> {
  hash?: T;
  config?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}