packages:
  - "apps/*"
  - "packages/*"
  - "worker"

allowBuilds:
  "@google/genai": false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sharp: true

onlyBuiltDependencies:
  - "@google/genai"
  - "esbuild"
  - "msgpackr-extract"
  - "protobufjs"
  - "sharp"
