import type { CollectionConfig } from "payload";

export const Configs: CollectionConfig = {
  slug: "configs",
  timestamps: true,
  admin: {
    useAsTitle: "id",
  },
  fields: [
    {
      name: "dataset",
      type: "relationship",
      relationTo: "datasets",
      required: true,
      index: true,
    },
    {
      name: "version",
      type: "number",
      required: true,
      defaultValue: 1,
    },
    {
      name: "config",
      type: "json",
      admin: {
        description: "Dashboard config. Never contains dataset rows.",
      },
    },
    {
      name: "insights",
      type: "json",
    },
    {
      // Section 13.4 requires the source of every config change to be stored.
      // A literal, not a user relationship: the initial pass is generated by the
      // pipeline with no user in the loop, and a prompt edit must be
      // distinguishable from it.
      name: "generatedBy",
      type: "select",
      required: true,
      defaultValue: "initial_auto_generation",
      options: [
        { label: "Initial auto generation", value: "initial_auto_generation" },
        { label: "Prompt edit", value: "prompt_edit" },
        { label: "Direct edit", value: "direct_edit" },
        { label: "Initial fallback (fast template)", value: "initial_fallback" },
      ],
    },
    {
      // Set only for prompt edits, so an auto-generated config is never
      // attributed to a user who did not ask for it.
      name: "editedBy",
      type: "relationship",
      relationTo: "users",
    },
  ],
};
